NEWSCHEMA('List', function(schema) {

	schema.addWorkflow('config', function($) {
		$.callback([{ name: 'allow_cache_cluster' }, { name: 'allow_cache_snapshot' }, { name: 'allow_clear_temp' }, { name: 'allow_compile' }, { name: 'allow_compile_html' }, { name: 'allow_compile_script' }, { name: 'allow_compile_style' }, { name: 'allow_custom_titles' }, { name: 'allow_debug' }, { name: 'allow_filter_errors' }, { name: 'allow_gzip' }, { name: 'allow_head' }, { name: 'allow_localize' }, { name: 'allow_performance' }, { name: 'allow_reqlimit' }, { name: 'allow_sessions_unused' }, { name: 'allow_ssc_validation' }, { name: 'allow_static_encryption' }, { name: 'allow_static_files' }, { name: 'allow_stats_snapshot' }, { name: 'allow_websocket' }, { name: 'allow_workers_silent' }, { name: 'author' }, { name: 'default_csrf_maxage' }, { name: 'default_cors' }, { name: 'default_cors_maxage' }, { name: 'default_crypto' }, { name: 'default_crypto_iv' }, { name: 'default_errorbuilder_resource_name' }, { name: 'default_errorbuilder_resource_prefix' }, { name: 'default_errorbuilder_status' }, { name: 'default_image_consumption' }, { name: 'default_image_converter' }, { name: 'default_image_quality' }, { name: 'default_interval_clear_cache' }, { name: 'default_interval_clear_dnscache' }, { name: 'default_interval_clear_resources' }, { name: 'default_interval_websocket_ping' }, { name: 'default_ip' }, { name: 'default_layout' }, { name: 'default_maxopenfiles' }, { name: 'default_port' }, { name: 'default_proxy' }, { name: 'default_request_maxkeys' }, { name: 'default_request_maxlength' }, { name: 'default_request_timeout' }, { name: 'default_response_maxage' }, { name: 'default_restbuilder_timeout' }, { name: 'default_root' }, { name: 'default_theme' }, { name: 'default_timezone' }, { name: 'default_websocket_encodedecode' }, { name: 'default_websocket_maxlength' }, { name: 'default_xpoweredby' }, { name: 'etag_version' }, { name: 'logger' }, { name: 'mail_api' }, { name: 'mail_bcc' }, { name: 'mail_cc' }, { name: 'mail_from' }, { name: 'mail_reply' }, { name: 'mail_smtp' }, { name: 'mail_smtp_options' }, { name: 'name' }, { name: 'secret' }, { name: 'secret_encryption' }, { name: 'secret_csrf' }, { name: 'secret_uid' }, { name: 'security.txt' }, { name: 'static_accepts' }, { name: 'static_accepts_custom' }, { name: 'static_url' }, { name: 'static_url_download' }, { name: 'static_url_font' }, { name: 'static_url_image' }, { name: 'static_url_script' }, { name: 'static_url_style' }, { name: 'static_url_video' }, { name: 'textdb_worker' }, { name: 'totalapi' }, { name: 'version' }, { name: 'default_errorbuilder_errors' }]);
	});

	schema.addWorkflow('modules', function($) {
		$.callback([{ name: 'https://cdn.totaljs.com/openplatform@1.js' }, { name: 'https://cdn.totaljs.com/totp@1.js' }, { name: 'https://cdn.totaljs.com/monitor@1.js' }, { name: 'https://cdn.totaljs.com/directorylisting@1.js' }]);
	});

});